### Setup & Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import torch
import regex as rg

In [3]:
from sentence_transformers import SentenceTransformer, util
from PIL import Image, ImageFile
import requests
import torch
import tqdm

In [4]:
torch.get_default_device()
dev = torch.device("mps" if torch.backends.mps.is_available() else  
                   "cuda" if torch.cuda.is_available() else "cpu")

In [5]:
img_model = SentenceTransformer('clip-ViT-B-32').to(dev)

# Our text embedding model is aligned to the img_model and maps 50+
# languages to the same vector space
text_model = SentenceTransformer('sentence-transformers/clip-ViT-B-32-multilingual-v1').to(dev)


def load_image(url_or_path):
    if url_or_path.startswith("http://") or url_or_path.startswith("https://"):
        return Image.open(requests.get(url_or_path, stream=True).raw)
    else:
        return Image.open(url_or_path)

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: /Users/benedikt/.cache/huggingface/hub/models--sentence-transformers--clip-ViT-B-32/snapshots/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/0_CLIPModel
Key                                  | Status     |  |
-------------------------------------+------------+--+-
text_model.embeddings.position_ids   | UNEXPECTED |  |
vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

In [6]:
import sys
sys.path.append(".")
from service.helpers import openImg

In [7]:
from service.model import Clipart, Base, N_EMBEDDINGS

In [8]:
base_folder="./cliparts"

In [9]:
from sqlalchemy import create_engine

conn_str = "postgresql://postgres:postgres@localhost:5431/postgres"
engine = create_engine(conn_str)

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

In [10]:
from pathlib import Path

img_paths = Path(base_folder).rglob("**/*.png")
imgs = pd.DataFrame({"path": img_paths})
imgs

                                                    path
0      cliparts/11_Stundenplan/14a0c82e-38fd-418c-b50...
1      cliparts/Transportmittel/Lokomotive_such a doo...
2                 cliparts/Blumen/Rose_such a doodle.png
3                cliparts/Blumen/Tulpe_such a doodle.png
4                   cliparts/Blumen/Sonnenhut_Ullala.png
...                                                  ...
28156  cliparts/Putzen/Putzlaune_Grundschulkritzelei/...
28157  cliparts/Putzen/Putzlaune_Grundschulkritzelei/...
28158  cliparts/Putzen/Putzlaune_Grundschulkritzelei/...
28159  cliparts/Putzen/Putzlaune_Grundschulkritzelei/...
28160  cliparts/Putzen/Putzlaune_Grundschulkritzelei/...

[28161 rows x 1 columns]

In [11]:
imgs["rel_path"] = imgs["path"].apply(lambda p: p.relative_to(base_folder))
imgs["rel_path"]

0        11_Stundenplan/14a0c82e-38fd-418c-b506-4620ded...
1             Transportmittel/Lokomotive_such a doodle.png
2                            Blumen/Rose_such a doodle.png
3                           Blumen/Tulpe_such a doodle.png
4                              Blumen/Sonnenhut_Ullala.png
                               ...
28156    Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...
28157    Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...
28158    Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...
28159    Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...
28160    Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...
Name: rel_path, Length: 28161, dtype: object

In [12]:
imgs['text']=imgs['rel_path'].apply(lambda p:" ".join(rg.split(r'[\\|/_\\.-]', str(p))).strip())
imgs['img_embeddings']=[[]]*imgs.shape[0]
imgs['txt_embeddings']=[[]]*imgs.shape[0]
imgs

,path,rel_path,text,img_embeddings,txt_embeddings
0,cliparts/11_Stundenplan/14a0c82e-38fd-418c-b50...,11_Stundenplan/14a0c82e-38fd-418c-b506-4620ded...,11 Stundenplan 14a0c82e 38fd 418c b506 4620ded...,[],[]
1,cliparts/Transportmittel/Lokomotive_such a doo...,Transportmittel/Lokomotive_such a doodle.png,Transportmittel Lokomotive such a doodle png,[],[]
2,cliparts/Blumen/Rose_such a doodle.png,Blumen/Rose_such a doodle.png,Blumen Rose such a doodle png,[],[]
3,cliparts/Blumen/Tulpe_such a doodle.png,Blumen/Tulpe_such a doodle.png,Blumen Tulpe such a doodle png,[],[]
4,cliparts/Blumen/Sonnenhut_Ullala.png,Blumen/Sonnenhut_Ullala.png,Blumen Sonnenhut Ullala png,[],[]
...,...,...,...,...,...
28156,cliparts/Putzen/Putzlaune_Grundschulkritzelei/...,Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...,Putzen Putzlaune Grundschulkritzelei KOLORIERT...,[],[]
28157,cliparts/Putzen/Putzlaune_Grundschulkritzelei/...,Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...,Putzen Putzlaune Grundschulkritzelei KOLORIERT...,[],[]
28158,cliparts/Putzen/Putzlaune_Grundschulkritzelei/...,Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...,Putzen Putzlaune Grundschulkritzelei KOLORIERT...,[],[]
28159,cliparts/Putzen/Putzlaune_Grundschulkritzelei/...,Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...,Putzen Putzlaune Grundschulkritzelei KOLORIERT...,[],[]
28160,cliparts/Putzen/Putzlaune_Grundschulkritzelei/...,Putzen/Putzlaune_Grundschulkritzelei/KOLORIERT...,Putzen Putzlaune Grundschulkritzelei KOLORIERT...,[],[]

In [13]:
from sqlalchemy.orm import Session


def encode_img_batch(img_paths):
    imgs = [openImg(img_path) for img_path in img_paths]
    img_embs = img_model.encode(imgs, convert_to_tensor=True)
    return img_embs


def encode_txt_batch(texts):
    txt_embs = text_model.encode(texts, convert_to_tensor=True)
    return txt_embs


def insert_embeddings(img_paths, img_embs, txt_embs, avg_embs):
    with Session(engine) as sess:
        for img_path, img_emb, txt_emb, avg_emb in zip(img_paths, img_embs, txt_embs, avg_embs):
            rel_path = Path(img_path).relative_to(base_folder)
            clipart = Clipart(
                path=str(rel_path),
                name=rel_path.stem,
                img_embedding=img_emb,
                text_embedding=txt_emb,
                avg_embedding=avg_emb,
            )
            sess.add(clipart)
        sess.commit()
        current_count = sess.query(Clipart).count()
        print(f"Inserted {len(img_paths)} embeddings. Total count: {current_count}")

In [14]:
n_batch = 128
g = imgs.index // n_batch
for idx, chunk in tqdm.tqdm(imgs.groupby(g), "encoding imgs"):
    img_dat = [openImg(img) for img in chunk["path"]]
    valid_idx = [i for i, img in enumerate(img_dat) if img is not None]
    # gather the valid images and their corresponding text as a dict
    img_dict = {
        i: {"img": img_dat[i], "text": chunk.iloc[i]["text"], "i": i, "path": chunk.iloc[i]["path"]} for i in valid_idx
    }
    def list_key(d, key):
        return [d[i][key] for i in d]

    img_embs = img_model.encode(list_key(img_dict, "img"), convert_to_tensor=True)

    txt_embs = encode_txt_batch(list_key(img_dict, "text"))
    avg_embs = (img_embs + txt_embs) / 2
    
    avg_embs = avg_embs.cpu().numpy().tolist()

    img_embs = img_embs.cpu().numpy().tolist()
    txt_embs = txt_embs.cpu().numpy().tolist()
    
    insert_embeddings(list_key(img_dict, "path"), img_embs, txt_embs, avg_embs)

encoding imgs:   0%|          | 1/221 [00:16<59:03, 16.11s/it]

Inserted 128 embeddings. Total count: 128

encoding imgs:   1%|          | 2/221 [00:28<50:37, 13.87s/it]

Inserted 128 embeddings. Total count: 256

/Users/benedikt/projects/mSUsIE/.venv/lib/python3.14/site-packages/PIL/Image.py:1034: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
encoding imgs:   1%|▏         | 3/221 [00:39<45:37, 12.56s/it]

Inserted 128 embeddings. Total count: 384

encoding imgs:   2%|▏         | 4/221 [00:57<53:21, 14.76s/it]

Inserted 128 embeddings. Total count: 512

encoding imgs:   2%|▏         | 5/221 [01:14<55:41, 15.47s/it]

Inserted 128 embeddings. Total count: 640

encoding imgs:   3%|▎         | 6/221 [01:31<57:05, 15.93s/it]

Inserted 128 embeddings. Total count: 768

encoding imgs:   3%|▎         | 7/221 [01:48<58:17, 16.34s/it]

Inserted 128 embeddings. Total count: 896

encoding imgs:   4%|▎         | 8/221 [01:58<51:37, 14.54s/it]

Inserted 128 embeddings. Total count: 1024

encoding imgs:   4%|▍         | 9/221 [02:10<48:10, 13.63s/it]

Inserted 128 embeddings. Total count: 1152

encoding imgs:   5%|▍         | 10/221 [02:16<39:34, 11.25s/it]

Inserted 128 embeddings. Total count: 1280

encoding imgs:   5%|▍         | 11/221 [02:30<42:32, 12.16s/it]

Inserted 128 embeddings. Total count: 1408

encoding imgs:   5%|▌         | 12/221 [03:15<1:17:15, 22.18s/it]

Inserted 128 embeddings. Total count: 1536

encoding imgs:   6%|▌         | 13/221 [03:50<1:29:43, 25.88s/it]

Inserted 128 embeddings. Total count: 1664

encoding imgs:   6%|▋         | 14/221 [04:25<1:39:13, 28.76s/it]

Inserted 128 embeddings. Total count: 1792

encoding imgs:   7%|▋         | 15/221 [04:43<1:27:56, 25.61s/it]

Inserted 128 embeddings. Total count: 1920

encoding imgs:   7%|▋         | 16/221 [05:03<1:21:23, 23.82s/it]

Inserted 128 embeddings. Total count: 2048

encoding imgs:   8%|▊         | 17/221 [05:21<1:15:13, 22.13s/it]

Inserted 128 embeddings. Total count: 2176

encoding imgs:   8%|▊         | 18/221 [05:41<1:12:01, 21.29s/it]

Inserted 128 embeddings. Total count: 2304

encoding imgs:   9%|▊         | 19/221 [05:54<1:03:45, 18.94s/it]

Inserted 128 embeddings. Total count: 2432

encoding imgs:   9%|▉         | 20/221 [06:09<59:46, 17.84s/it]

Inserted 128 embeddings. Total count: 2560

encoding imgs:  10%|▉         | 21/221 [06:24<56:31, 16.96s/it]

Inserted 128 embeddings. Total count: 2688

encoding imgs:  10%|▉         | 22/221 [06:44<58:28, 17.63s/it]

Inserted 128 embeddings. Total count: 2816

encoding imgs:  10%|█         | 23/221 [06:59<55:42, 16.88s/it]

Inserted 128 embeddings. Total count: 2944

encoding imgs:  11%|█         | 24/221 [07:12<52:11, 15.90s/it]

Inserted 128 embeddings. Total count: 3072

encoding imgs:  11%|█▏        | 25/221 [07:26<50:17, 15.40s/it]

Inserted 128 embeddings. Total count: 3200

encoding imgs:  12%|█▏        | 26/221 [07:46<53:44, 16.53s/it]

Inserted 128 embeddings. Total count: 3328

encoding imgs:  12%|█▏        | 27/221 [08:05<56:23, 17.44s/it]

Inserted 128 embeddings. Total count: 3456

encoding imgs:  13%|█▎        | 28/221 [08:21<54:19, 16.89s/it]

Inserted 128 embeddings. Total count: 3584

encoding imgs:  13%|█▎        | 29/221 [08:37<53:11, 16.62s/it]

Inserted 128 embeddings. Total count: 3712

encoding imgs:  14%|█▎        | 30/221 [08:57<55:50, 17.54s/it]

Inserted 128 embeddings. Total count: 3840

encoding imgs:  14%|█▍        | 31/221 [09:11<53:06, 16.77s/it]

Inserted 128 embeddings. Total count: 3968

encoding imgs:  14%|█▍        | 32/221 [09:34<58:22, 18.53s/it]

Inserted 128 embeddings. Total count: 4096

encoding imgs:  15%|█▍        | 33/221 [09:54<59:09, 18.88s/it]

Inserted 128 embeddings. Total count: 4224

encoding imgs:  15%|█▌        | 34/221 [10:08<54:54, 17.62s/it]

Inserted 128 embeddings. Total count: 4352

encoding imgs:  16%|█▌        | 35/221 [10:28<56:20, 18.17s/it]

Inserted 128 embeddings. Total count: 4480

encoding imgs:  16%|█▋        | 36/221 [11:19<1:26:51, 28.17s/it]

Inserted 128 embeddings. Total count: 4608

encoding imgs:  17%|█▋        | 37/221 [11:32<1:12:16, 23.57s/it]

Inserted 128 embeddings. Total count: 4736

encoding imgs:  17%|█▋        | 38/221 [11:50<1:06:40, 21.86s/it]

Inserted 128 embeddings. Total count: 4864

encoding imgs:  18%|█▊        | 39/221 [12:06<1:01:17, 20.21s/it]

Inserted 128 embeddings. Total count: 4992

encoding imgs:  18%|█▊        | 40/221 [12:12<47:59, 15.91s/it]

Inserted 128 embeddings. Total count: 5120

encoding imgs:  19%|█▊        | 41/221 [12:16<36:26, 12.15s/it]

Inserted 128 embeddings. Total count: 5248

encoding imgs:  19%|█▉        | 42/221 [12:20<28:50,  9.67s/it]

Inserted 128 embeddings. Total count: 5376

encoding imgs:  19%|█▉        | 43/221 [12:23<23:11,  7.82s/it]

Inserted 128 embeddings. Total count: 5504

encoding imgs:  20%|█▉        | 44/221 [12:27<19:32,  6.63s/it]

Inserted 128 embeddings. Total count: 5632

encoding imgs:  20%|██        | 45/221 [12:31<16:50,  5.74s/it]

Inserted 128 embeddings. Total count: 5760

encoding imgs:  21%|██        | 46/221 [12:34<14:30,  4.98s/it]

Inserted 128 embeddings. Total count: 5888

encoding imgs:  21%|██▏       | 47/221 [12:38<13:41,  4.72s/it]

Inserted 128 embeddings. Total count: 6016

encoding imgs:  22%|██▏       | 48/221 [12:42<13:17,  4.61s/it]

Inserted 128 embeddings. Total count: 6144

encoding imgs:  22%|██▏       | 49/221 [12:45<11:39,  4.07s/it]

Inserted 128 embeddings. Total count: 6272

encoding imgs:  23%|██▎       | 50/221 [12:50<11:56,  4.19s/it]

Inserted 128 embeddings. Total count: 6400

encoding imgs:  23%|██▎       | 51/221 [12:52<10:27,  3.69s/it]

Inserted 128 embeddings. Total count: 6528

encoding imgs:  24%|██▎       | 52/221 [12:56<10:15,  3.64s/it]

Inserted 128 embeddings. Total count: 6656

encoding imgs:  24%|██▍       | 53/221 [12:59<10:19,  3.69s/it]

Inserted 128 embeddings. Total count: 6784

encoding imgs:  24%|██▍       | 54/221 [13:03<10:17,  3.70s/it]

Inserted 128 embeddings. Total count: 6912

encoding imgs:  25%|██▍       | 55/221 [13:07<10:11,  3.68s/it]

Inserted 128 embeddings. Total count: 7040

encoding imgs:  25%|██▌       | 56/221 [13:10<09:58,  3.63s/it]

Inserted 128 embeddings. Total count: 7168

encoding imgs:  26%|██▌       | 57/221 [13:14<10:08,  3.71s/it]

Inserted 128 embeddings. Total count: 7296

encoding imgs:  26%|██▌       | 58/221 [13:20<11:27,  4.22s/it]

Inserted 128 embeddings. Total count: 7424

encoding imgs:  27%|██▋       | 59/221 [13:23<10:53,  4.03s/it]

Inserted 128 embeddings. Total count: 7552

encoding imgs:  27%|██▋       | 60/221 [13:28<11:10,  4.16s/it]

Inserted 128 embeddings. Total count: 7680

encoding imgs:  28%|██▊       | 61/221 [13:34<12:47,  4.79s/it]

Inserted 128 embeddings. Total count: 7808

encoding imgs:  28%|██▊       | 62/221 [13:37<11:20,  4.28s/it]

Inserted 128 embeddings. Total count: 7936

encoding imgs:  29%|██▊       | 63/221 [13:41<10:55,  4.15s/it]

Inserted 128 embeddings. Total count: 8064

encoding imgs:  29%|██▉       | 64/221 [13:46<11:51,  4.54s/it]

Inserted 128 embeddings. Total count: 8192

encoding imgs:  29%|██▉       | 65/221 [13:52<13:01,  5.01s/it]

Inserted 128 embeddings. Total count: 8320

encoding imgs:  30%|██▉       | 66/221 [13:56<11:47,  4.56s/it]

Inserted 128 embeddings. Total count: 8448

encoding imgs:  30%|███       | 67/221 [13:59<10:21,  4.04s/it]

Inserted 128 embeddings. Total count: 8576

encoding imgs:  31%|███       | 68/221 [14:02<09:30,  3.73s/it]

Inserted 128 embeddings. Total count: 8704

encoding imgs:  31%|███       | 69/221 [14:13<15:27,  6.10s/it]

Inserted 128 embeddings. Total count: 8832

encoding imgs:  32%|███▏      | 70/221 [14:18<14:34,  5.79s/it]

Inserted 128 embeddings. Total count: 8960

encoding imgs:  32%|███▏      | 71/221 [14:23<13:14,  5.30s/it]

Inserted 128 embeddings. Total count: 9088

encoding imgs:  33%|███▎      | 72/221 [14:26<11:42,  4.72s/it]

Inserted 128 embeddings. Total count: 9216

encoding imgs:  33%|███▎      | 73/221 [14:31<11:48,  4.79s/it]

Inserted 128 embeddings. Total count: 9344

encoding imgs:  33%|███▎      | 74/221 [14:36<11:49,  4.83s/it]

Inserted 128 embeddings. Total count: 9472

encoding imgs:  34%|███▍      | 75/221 [14:40<11:10,  4.59s/it]

Inserted 128 embeddings. Total count: 9600

encoding imgs:  34%|███▍      | 76/221 [14:46<11:50,  4.90s/it]

Inserted 128 embeddings. Total count: 9728

encoding imgs:  35%|███▍      | 77/221 [14:51<12:06,  5.04s/it]

Inserted 128 embeddings. Total count: 9856

encoding imgs:  35%|███▌      | 78/221 [14:54<10:50,  4.55s/it]

Inserted 128 embeddings. Total count: 9984

encoding imgs:  36%|███▌      | 79/221 [14:57<09:35,  4.05s/it]

Inserted 128 embeddings. Total count: 10112

encoding imgs:  36%|███▌      | 80/221 [15:00<08:37,  3.67s/it]

Inserted 128 embeddings. Total count: 10240

encoding imgs:  37%|███▋      | 81/221 [15:06<10:18,  4.41s/it]

Inserted 128 embeddings. Total count: 10368

encoding imgs:  37%|███▋      | 82/221 [15:10<09:33,  4.13s/it]

Inserted 128 embeddings. Total count: 10496

encoding imgs:  38%|███▊      | 83/221 [15:13<08:41,  3.78s/it]

Inserted 128 embeddings. Total count: 10624

encoding imgs:  38%|███▊      | 84/221 [15:16<08:40,  3.80s/it]

Inserted 128 embeddings. Total count: 10752

encoding imgs:  38%|███▊      | 85/221 [15:23<10:48,  4.77s/it]

Inserted 128 embeddings. Total count: 10880

encoding imgs:  39%|███▉      | 86/221 [15:28<10:32,  4.68s/it]

Inserted 128 embeddings. Total count: 11008

encoding imgs:  39%|███▉      | 87/221 [15:33<10:26,  4.68s/it]

Inserted 128 embeddings. Total count: 11136

encoding imgs:  40%|███▉      | 88/221 [15:36<09:18,  4.20s/it]

Inserted 128 embeddings. Total count: 11264

encoding imgs:  40%|████      | 89/221 [15:39<08:43,  3.97s/it]

Inserted 128 embeddings. Total count: 11392

encoding imgs:  41%|████      | 90/221 [15:42<07:56,  3.64s/it]

Inserted 128 embeddings. Total count: 11520

encoding imgs:  41%|████      | 91/221 [15:45<07:38,  3.53s/it]

Inserted 128 embeddings. Total count: 11648

encoding imgs:  42%|████▏     | 92/221 [15:48<06:58,  3.25s/it]

Inserted 128 embeddings. Total count: 11776

encoding imgs:  42%|████▏     | 93/221 [15:50<06:33,  3.07s/it]

Inserted 128 embeddings. Total count: 11904

encoding imgs:  43%|████▎     | 94/221 [15:53<06:03,  2.86s/it]

Inserted 128 embeddings. Total count: 12032

encoding imgs:  43%|████▎     | 95/221 [15:56<05:54,  2.81s/it]

Inserted 128 embeddings. Total count: 12160

encoding imgs:  43%|████▎     | 96/221 [15:58<05:32,  2.66s/it]

Inserted 128 embeddings. Total count: 12288

encoding imgs:  44%|████▍     | 97/221 [16:00<05:18,  2.57s/it]

Inserted 128 embeddings. Total count: 12416

encoding imgs:  44%|████▍     | 98/221 [16:04<05:48,  2.83s/it]

Inserted 128 embeddings. Total count: 12544

encoding imgs:  45%|████▍     | 99/221 [16:06<05:38,  2.77s/it]

Inserted 128 embeddings. Total count: 12672

encoding imgs:  45%|████▌     | 100/221 [16:10<06:05,  3.02s/it]

Inserted 128 embeddings. Total count: 12800

encoding imgs:  46%|████▌     | 101/221 [16:16<07:53,  3.94s/it]

Inserted 128 embeddings. Total count: 12928

encoding imgs:  46%|████▌     | 102/221 [16:19<07:22,  3.72s/it]

Inserted 128 embeddings. Total count: 13056

encoding imgs:  47%|████▋     | 103/221 [16:21<06:08,  3.12s/it]

Inserted 128 embeddings. Total count: 13184

encoding imgs:  47%|████▋     | 104/221 [16:26<07:26,  3.82s/it]

Inserted 128 embeddings. Total count: 13312

encoding imgs:  48%|████▊     | 105/221 [16:31<07:40,  3.97s/it]

Inserted 128 embeddings. Total count: 13440

encoding imgs:  48%|████▊     | 106/221 [16:37<09:12,  4.80s/it]

Inserted 128 embeddings. Total count: 13568

encoding imgs:  48%|████▊     | 107/221 [16:43<09:34,  5.04s/it]

Inserted 128 embeddings. Total count: 13696

encoding imgs:  49%|████▉     | 108/221 [16:49<10:10,  5.40s/it]

Inserted 128 embeddings. Total count: 13824

encoding imgs:  49%|████▉     | 109/221 [16:54<09:55,  5.32s/it]

Inserted 128 embeddings. Total count: 13952

encoding imgs:  50%|████▉     | 110/221 [17:00<10:03,  5.44s/it]

Inserted 128 embeddings. Total count: 14080

encoding imgs:  50%|█████     | 111/221 [17:04<08:55,  4.87s/it]

Inserted 128 embeddings. Total count: 14208

encoding imgs:  51%|█████     | 112/221 [17:06<07:42,  4.25s/it]

Inserted 128 embeddings. Total count: 14336

encoding imgs:  51%|█████     | 113/221 [17:10<07:18,  4.06s/it]

Inserted 128 embeddings. Total count: 14464

encoding imgs:  52%|█████▏    | 114/221 [17:13<06:40,  3.74s/it]

Inserted 128 embeddings. Total count: 14592

encoding imgs:  52%|█████▏    | 115/221 [17:17<06:43,  3.81s/it]

Inserted 128 embeddings. Total count: 14720

encoding imgs:  52%|█████▏    | 116/221 [17:24<08:12,  4.69s/it]

Inserted 128 embeddings. Total count: 14848

encoding imgs:  53%|█████▎    | 117/221 [17:27<07:28,  4.31s/it]

Inserted 128 embeddings. Total count: 14976

encoding imgs:  53%|█████▎    | 118/221 [17:31<06:59,  4.07s/it]

Inserted 128 embeddings. Total count: 15104

encoding imgs:  54%|█████▍    | 119/221 [17:35<07:02,  4.14s/it]

Inserted 128 embeddings. Total count: 15232

encoding imgs:  54%|█████▍    | 120/221 [17:38<06:12,  3.68s/it]

Inserted 128 embeddings. Total count: 15360

encoding imgs:  55%|█████▍    | 121/221 [17:41<06:10,  3.70s/it]

Inserted 128 embeddings. Total count: 15488

encoding imgs:  55%|█████▌    | 122/221 [17:46<06:21,  3.85s/it]

Inserted 128 embeddings. Total count: 15616

encoding imgs:  56%|█████▌    | 123/221 [17:51<06:55,  4.23s/it]

Inserted 128 embeddings. Total count: 15744

encoding imgs:  56%|█████▌    | 124/221 [17:56<07:33,  4.67s/it]

Inserted 128 embeddings. Total count: 15872

encoding imgs:  57%|█████▋    | 125/221 [17:59<06:43,  4.20s/it]

Inserted 128 embeddings. Total count: 16000

encoding imgs:  57%|█████▋    | 126/221 [18:03<06:19,  3.99s/it]

Inserted 128 embeddings. Total count: 16128

encoding imgs:  57%|█████▋    | 127/221 [18:06<05:56,  3.79s/it]

Inserted 128 embeddings. Total count: 16256

encoding imgs:  58%|█████▊    | 128/221 [18:14<07:31,  4.85s/it]

Inserted 128 embeddings. Total count: 16384

encoding imgs:  58%|█████▊    | 129/221 [18:19<07:39,  5.00s/it]

Inserted 128 embeddings. Total count: 16512

encoding imgs:  59%|█████▉    | 130/221 [18:23<07:08,  4.71s/it]

Inserted 128 embeddings. Total count: 16640

encoding imgs:  59%|█████▉    | 131/221 [18:27<06:33,  4.38s/it]

Inserted 128 embeddings. Total count: 16768

encoding imgs:  60%|█████▉    | 132/221 [18:31<06:29,  4.38s/it]

Inserted 128 embeddings. Total count: 16896

encoding imgs:  60%|██████    | 133/221 [18:36<06:34,  4.48s/it]

Inserted 128 embeddings. Total count: 17024

encoding imgs:  61%|██████    | 134/221 [18:39<05:55,  4.09s/it]

Inserted 128 embeddings. Total count: 17152

encoding imgs:  61%|██████    | 135/221 [18:42<05:23,  3.76s/it]

Inserted 128 embeddings. Total count: 17280

encoding imgs:  62%|██████▏   | 136/221 [18:46<05:33,  3.92s/it]

Inserted 128 embeddings. Total count: 17408

encoding imgs:  62%|██████▏   | 137/221 [18:50<05:23,  3.85s/it]

Inserted 128 embeddings. Total count: 17536

encoding imgs:  62%|██████▏   | 138/221 [18:54<05:32,  4.01s/it]

Inserted 128 embeddings. Total count: 17664

encoding imgs:  63%|██████▎   | 139/221 [18:57<04:51,  3.55s/it]

Inserted 128 embeddings. Total count: 17792

encoding imgs:  63%|██████▎   | 140/221 [19:00<04:45,  3.52s/it]

Inserted 128 embeddings. Total count: 17920

encoding imgs:  64%|██████▍   | 141/221 [19:06<05:43,  4.30s/it]

Inserted 128 embeddings. Total count: 18048

encoding imgs:  64%|██████▍   | 142/221 [19:11<05:52,  4.46s/it]

Inserted 128 embeddings. Total count: 18176

encoding imgs:  65%|██████▍   | 143/221 [19:15<05:30,  4.24s/it]

Inserted 128 embeddings. Total count: 18304

encoding imgs:  65%|██████▌   | 144/221 [19:19<05:27,  4.25s/it]

Inserted 128 embeddings. Total count: 18432

encoding imgs:  66%|██████▌   | 145/221 [19:23<05:09,  4.07s/it]

Inserted 128 embeddings. Total count: 18560

encoding imgs:  66%|██████▌   | 146/221 [19:27<05:19,  4.25s/it]

Inserted 128 embeddings. Total count: 18688

encoding imgs:  67%|██████▋   | 147/221 [19:30<04:44,  3.85s/it]

Inserted 128 embeddings. Total count: 18816

encoding imgs:  67%|██████▋   | 148/221 [19:35<04:51,  4.00s/it]

Inserted 128 embeddings. Total count: 18944

encoding imgs:  67%|██████▋   | 149/221 [19:39<04:54,  4.09s/it]

Inserted 128 embeddings. Total count: 19072

encoding imgs:  68%|██████▊   | 150/221 [19:41<04:05,  3.46s/it]

Inserted 128 embeddings. Total count: 19200

encoding imgs:  68%|██████▊   | 151/221 [19:43<03:24,  2.92s/it]

Inserted 128 embeddings. Total count: 19328

encoding imgs:  69%|██████▉   | 152/221 [19:47<03:52,  3.37s/it]

Inserted 128 embeddings. Total count: 19456

encoding imgs:  69%|██████▉   | 153/221 [19:51<04:08,  3.65s/it]

Inserted 128 embeddings. Total count: 19584

encoding imgs:  70%|██████▉   | 154/221 [19:53<03:21,  3.01s/it]

Inserted 128 embeddings. Total count: 19712

encoding imgs:  70%|███████   | 155/221 [19:56<03:28,  3.15s/it]

Inserted 128 embeddings. Total count: 19840

encoding imgs:  71%|███████   | 156/221 [20:00<03:26,  3.17s/it]

Inserted 128 embeddings. Total count: 19968

encoding imgs:  71%|███████   | 157/221 [20:04<03:49,  3.59s/it]

Inserted 128 embeddings. Total count: 20096

encoding imgs:  71%|███████▏  | 158/221 [20:07<03:40,  3.49s/it]

Inserted 128 embeddings. Total count: 20224

encoding imgs:  72%|███████▏  | 159/221 [20:11<03:35,  3.48s/it]

Inserted 128 embeddings. Total count: 20352

encoding imgs:  72%|███████▏  | 160/221 [20:16<04:10,  4.10s/it]

Inserted 128 embeddings. Total count: 20480

encoding imgs:  73%|███████▎  | 161/221 [20:21<04:07,  4.12s/it]

Inserted 128 embeddings. Total count: 20608

encoding imgs:  73%|███████▎  | 162/221 [20:26<04:30,  4.59s/it]

Inserted 128 embeddings. Total count: 20736

encoding imgs:  74%|███████▍  | 163/221 [20:32<04:38,  4.80s/it]

Inserted 128 embeddings. Total count: 20864

encoding imgs:  74%|███████▍  | 164/221 [20:35<04:01,  4.24s/it]

Inserted 128 embeddings. Total count: 20992

encoding imgs:  75%|███████▍  | 165/221 [20:38<03:40,  3.93s/it]

Inserted 128 embeddings. Total count: 21120

encoding imgs:  75%|███████▌  | 166/221 [20:41<03:28,  3.80s/it]

Inserted 128 embeddings. Total count: 21248

encoding imgs:  76%|███████▌  | 167/221 [20:46<03:35,  4.00s/it]

Inserted 128 embeddings. Total count: 21376

encoding imgs:  76%|███████▌  | 168/221 [20:48<03:07,  3.54s/it]

Inserted 128 embeddings. Total count: 21504

encoding imgs:  76%|███████▋  | 169/221 [20:52<03:06,  3.60s/it]

Inserted 128 embeddings. Total count: 21632

encoding imgs:  77%|███████▋  | 170/221 [20:57<03:23,  3.98s/it]

Inserted 128 embeddings. Total count: 21760

encoding imgs:  77%|███████▋  | 171/221 [21:03<03:47,  4.54s/it]

Inserted 128 embeddings. Total count: 21888

encoding imgs:  78%|███████▊  | 172/221 [21:07<03:41,  4.53s/it]

Inserted 128 embeddings. Total count: 22016

encoding imgs:  78%|███████▊  | 173/221 [21:11<03:23,  4.24s/it]

Inserted 128 embeddings. Total count: 22144

encoding imgs:  79%|███████▊  | 174/221 [21:15<03:16,  4.18s/it]

Inserted 128 embeddings. Total count: 22272

encoding imgs:  79%|███████▉  | 175/221 [21:18<02:54,  3.80s/it]

Inserted 128 embeddings. Total count: 22400

encoding imgs:  80%|███████▉  | 176/221 [21:22<03:00,  4.02s/it]

Inserted 128 embeddings. Total count: 22528

encoding imgs:  80%|████████  | 177/221 [21:25<02:38,  3.61s/it]

Inserted 128 embeddings. Total count: 22656

encoding imgs:  81%|████████  | 178/221 [21:27<02:23,  3.33s/it]

Inserted 128 embeddings. Total count: 22784

encoding imgs:  81%|████████  | 179/221 [21:31<02:20,  3.34s/it]

Inserted 128 embeddings. Total count: 22912

encoding imgs:  81%|████████▏ | 180/221 [21:45<04:35,  6.71s/it]

Inserted 128 embeddings. Total count: 23040

encoding imgs:  82%|████████▏ | 181/221 [21:51<04:14,  6.36s/it]

Inserted 128 embeddings. Total count: 23168

encoding imgs:  82%|████████▏ | 182/221 [21:56<03:48,  5.86s/it]

Inserted 128 embeddings. Total count: 23296

encoding imgs:  83%|████████▎ | 183/221 [22:05<04:17,  6.77s/it]

Inserted 128 embeddings. Total count: 23424

encoding imgs:  83%|████████▎ | 184/221 [22:12<04:21,  7.08s/it]

Inserted 128 embeddings. Total count: 23552

encoding imgs:  84%|████████▎ | 185/221 [22:18<04:02,  6.73s/it]

Inserted 128 embeddings. Total count: 23680

encoding imgs:  84%|████████▍ | 186/221 [22:24<03:42,  6.37s/it]

Inserted 128 embeddings. Total count: 23808

encoding imgs:  85%|████████▍ | 187/221 [22:28<03:16,  5.77s/it]

Inserted 128 embeddings. Total count: 23936

encoding imgs:  85%|████████▌ | 188/221 [22:32<02:55,  5.32s/it]

Inserted 128 embeddings. Total count: 24064

encoding imgs:  86%|████████▌ | 189/221 [22:36<02:29,  4.66s/it]

Inserted 128 embeddings. Total count: 24192

encoding imgs:  86%|████████▌ | 190/221 [22:39<02:11,  4.24s/it]

Inserted 128 embeddings. Total count: 24320

encoding imgs:  86%|████████▋ | 191/221 [22:41<01:51,  3.72s/it]

Inserted 128 embeddings. Total count: 24448

encoding imgs:  87%|████████▋ | 192/221 [22:45<01:46,  3.68s/it]

Inserted 128 embeddings. Total count: 24576

encoding imgs:  87%|████████▋ | 193/221 [22:48<01:42,  3.65s/it]

Inserted 128 embeddings. Total count: 24704

encoding imgs:  88%|████████▊ | 194/221 [22:52<01:34,  3.51s/it]

Inserted 128 embeddings. Total count: 24832

encoding imgs:  88%|████████▊ | 195/221 [22:54<01:25,  3.29s/it]

Inserted 128 embeddings. Total count: 24960

encoding imgs:  89%|████████▊ | 196/221 [22:56<01:12,  2.89s/it]

Inserted 128 embeddings. Total count: 25088

encoding imgs:  89%|████████▉ | 197/221 [23:01<01:20,  3.35s/it]

Inserted 128 embeddings. Total count: 25216

encoding imgs:  90%|████████▉ | 198/221 [23:04<01:13,  3.20s/it]

Inserted 128 embeddings. Total count: 25344

encoding imgs:  90%|█████████ | 199/221 [23:07<01:09,  3.15s/it]

Inserted 128 embeddings. Total count: 25472

encoding imgs:  90%|█████████ | 200/221 [23:10<01:10,  3.35s/it]

Inserted 128 embeddings. Total count: 25600

encoding imgs:  91%|█████████ | 201/221 [23:15<01:15,  3.77s/it]

Inserted 128 embeddings. Total count: 25728

encoding imgs:  91%|█████████▏| 202/221 [23:19<01:12,  3.81s/it]

Inserted 128 embeddings. Total count: 25856

encoding imgs:  92%|█████████▏| 203/221 [23:25<01:20,  4.45s/it]

Inserted 128 embeddings. Total count: 25984

encoding imgs:  92%|█████████▏| 204/221 [23:29<01:12,  4.27s/it]

Inserted 128 embeddings. Total count: 26112

encoding imgs:  93%|█████████▎| 205/221 [23:33<01:08,  4.28s/it]

Inserted 128 embeddings. Total count: 26240

encoding imgs:  93%|█████████▎| 206/221 [23:37<01:02,  4.14s/it]

Inserted 128 embeddings. Total count: 26368

encoding imgs:  94%|█████████▎| 207/221 [23:41<00:56,  4.05s/it]

Inserted 128 embeddings. Total count: 26496

encoding imgs:  94%|█████████▍| 208/221 [23:44<00:49,  3.80s/it]

Inserted 128 embeddings. Total count: 26624

encoding imgs:  95%|█████████▍| 209/221 [23:58<01:22,  6.90s/it]

Inserted 128 embeddings. Total count: 26752

encoding imgs:  95%|█████████▌| 210/221 [24:15<01:46,  9.73s/it]

Inserted 128 embeddings. Total count: 26880

encoding imgs:  95%|█████████▌| 211/221 [24:21<01:28,  8.85s/it]

Inserted 128 embeddings. Total count: 27008

encoding imgs:  96%|█████████▌| 212/221 [24:26<01:07,  7.51s/it]

Inserted 128 embeddings. Total count: 27136

encoding imgs:  96%|█████████▋| 213/221 [24:34<01:01,  7.68s/it]

Inserted 128 embeddings. Total count: 27264

encoding imgs:  97%|█████████▋| 214/221 [24:40<00:51,  7.33s/it]

Inserted 128 embeddings. Total count: 27392

encoding imgs:  97%|█████████▋| 215/221 [24:54<00:54,  9.12s/it]

Inserted 128 embeddings. Total count: 27520

encoding imgs:  98%|█████████▊| 216/221 [25:01<00:42,  8.58s/it]

Inserted 128 embeddings. Total count: 27648

encoding imgs:  98%|█████████▊| 217/221 [25:04<00:27,  6.82s/it]

Inserted 128 embeddings. Total count: 27776

encoding imgs:  99%|█████████▊| 218/221 [25:10<00:19,  6.64s/it]

Inserted 128 embeddings. Total count: 27904

encoding imgs:  99%|█████████▉| 219/221 [25:16<00:13,  6.51s/it]

Inserted 128 embeddings. Total count: 28032

encoding imgs: 100%|█████████▉| 220/221 [25:25<00:07,  7.18s/it]

Inserted 128 embeddings. Total count: 28160

encoding imgs: 100%|██████████| 221/221 [25:25<00:00,  6.90s/it]

Inserted 1 embeddings. Total count: 28161

In [15]:
with Session(engine) as conn:
    cliparts = conn.query(Clipart).count()
    print(f"Inserted {cliparts} cliparts into the database.")

Inserted 28161 cliparts into the database.

In [16]:
len(img_embs)

1

In [17]:
def query_model1(query: str, count: int = 10, draw = False):
    global cliparts
    global cliparts_txt
    hits = []

    result=cliparts.search(
        [text_model.encode(query)],
        anns_field="img_embeddings",
        limit=count,
        param={"metric_type": "COSINE", "params": {"nprobe": 2}},
        output_fields=["path", "text"],
    )

    result=result[0]

    if draw is False:
        for i,hit in enumerate(result):
            hits.append(hit.entity.get('text'))
    else:
        fig,ax=plt.subplots(1,count)
        fig.set_figwidth(20)
        fig.set_figheight(5)
        for i,hit in enumerate(result):
            img=np.asarray(Image.open(hit.entity.get('path')))
            if img.shape[-1]<3:
                img=img[...,0]
            ax[i].imshow(img, cmap='gray')
            ax[i].set_axis_off()
            hits.append(hit.entity.get('text'))
    return hits  

hits = query_model1("hund", 10, True)   
print(hits)

AttributeError: 'int' object has no attribute 'search'